### ISSUE TITLE
Seen handling

### ISSUE THREAD

**Issue by haydencheers** [FleetingMotivations/FleetServer#10]
In Heartbeat messages are marked as seen. This stops them from being requested in the QueryFiles method. 

Two proposed methods:
1. Add another field 'HasRequested' to Message. This will allow the HasSeen value to be set in the heartbeat, and then allow for HasRequested to be set in the RequestFile method.
2. Stop setting the 'HasSeen' value in the Heartbeat

**Comment by twisty-n** [comment]
@me Check if Received is nullable, if it is, use it as the search key
