### ISSUE TITLE
Polymorphism in database queries

### ISSUE THREAD

**Issue by haydencheers** [FleetingMotivations/FleetServer#11]
In a LINQ query it appears that objects are not actually of one of the generated model types, but a dynamic proxy subclass of that type. As such any 'GetType() == typeof(Type)' do not work as expected.

The easiest fix for this is to replace any 'GetType() == typeof(Type)' with 'is Type'.

**Comment by twisty-n** [comment]
@me `ToList()` should force resolution. If not, check this, and investigate `is Type` approach
