### ISSUE TITLE
Heartbeat Changes that are good enough for an Issue

### ISSUE THREAD

**Issue by haydencheers** [FleetingMotivations/FleetServer#8]
Here's the Issue:
- Remove known clients from heartbeat method
- Flag enum addition to show workgroup has changed?
- Implement query clients method
- When in workgroup, return all in that workgroup. Otherwise all in room.
- FleetFileIdentifier - Need sender name?

**Comment by twisty-n** [comment]
1/5 implemented in https://github.com/FleetingMotivations/FleetServer/pull/9

3 is not an issue
